import Atom from '../../../services/Atom'

export const Button = Atom.create('button')
export const Div = Atom.create('div')
export const Form = Atom.create('form')
export const H1 = Atom.create('h1')
export const H3 = Atom.create('h3')
export const Header = Atom.create('header')
export const Img = Atom.create('img')
export const Input = Atom.create('input')
export const Label = Atom.create('label')
export const Li = Atom.create('li')
export const Nav = Atom.create('nav')
export const P = Atom.create('p')
export const Path = Atom.create('path')
export const Section = Atom.create('section')
export const Span = Atom.create('span')
export const Svg = Atom.create('svg')
export const Textarea = Atom.create('textarea')
export const Ul = Atom.create('ul')
